-- Banco de palabras candidatas que terminan en "x".
-- El juego puede aceptar o rechazar algunas según su diccionario;
-- las rechazadas deben terminar en BlacklistedWords.

return {
    "affix",
    "annex",
    "apex",
    "appendix",
    "borax",
    "box",
    "calyx",
    "climax",
    "coax",
    "complex",
    "crux",
    "detox",
    "duplex",
    "equinox",
    "fax",
    "fix",
    "flex",
    "flux",
    "fox",
    "helix",
    "hex",
    "hoax",
    "ibex",
    "index",
    "latex",
    "lynx",
    "matrix",
    "max",
    "mix",
    "onyx",
    "paradox",
    "phoenix",
    "prefix",
    "reflex",
    "remix",
    "simplex",
    "six",
    "sphinx",
    "suffix",
    "syntax",
    "tax",
    "thorax",
    "transfix",
    "triplex",
    "vex",
    "vortex",
    "wax",
}
